---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	plan_node(plan_node)
	tool_node(tool_node)
	research_gate_node(research_gate_node)
	deep_fetch_node(deep_fetch_node)
	followup_search_node(followup_search_node)
	finalize_node(finalize_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> plan_node;
	deep_fetch_node -.-> research_gate_node;
	deep_fetch_node -.-> tool_node;
	followup_search_node -.-> research_gate_node;
	followup_search_node -.-> tool_node;
	plan_node -. &nbsp;__end__&nbsp; .-> research_gate_node;
	plan_node -. &nbsp;tools&nbsp; .-> tool_node;
	research_gate_node -. &nbsp;deep_fetch&nbsp; .-> deep_fetch_node;
	research_gate_node -. &nbsp;finalize&nbsp; .-> finalize_node;
	research_gate_node -. &nbsp;followup_search&nbsp; .-> followup_search_node;
	tool_node --> research_gate_node;
	finalize_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

